In [13]:
import numpy as np

#  1: To Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# 2: To Reshape the array to a 3x5 matrix
reshaped_array = random_vector.reshape(3, 5)

# 3: To Print the shape of the array
print("Array shape:", reshaped_array.shape)

# Step 4: Replace the maximum value in each row with 0
for i in range(reshaped_array.shape[0]):
    max_index = np.argmax(reshaped_array[i])
    reshaped_array[i][max_index] = 0
    #find the index of the maximum value in that row. Then, you replace the maximum value in that row with 0.

# Print the modified array
print("Modified array:")
print(reshaped_array)


Array shape: (3, 5)
Modified array:
[[ 8  7  0  4 13]
 [ 0 15 19  6  4]
 [ 9 14  0 14 16]]


In [2]:
import numpy as np

# Create a 2-dimensional array of size 4x3 with 4-byte integer elements
array_2d = np.zeros((4, 3), dtype=np.int32)

# Print the shape of the array
print("Array shape:", array_2d.shape)

# Print the type of the array
print("Array type:", type(array_2d))

# Print the data type of the array elements
print("Data type of array elements:", array_2d.dtype)


Array shape: (4, 3)
Array type: <class 'numpy.ndarray'>
Data type of array elements: int32


In [3]:
import numpy as np

# Create the array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(array)

# Print the result
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [8]:
import numpy as np

# Create an array of even numbers between 10 and 70
even_numbers = np.arange(10, 71, 2)

# Create an array of odd numbers between 10 and 70
odd_numbers = np.arange(11, 71, 2)

print("Even Numbers:")
print(even_numbers)

print("Odd Numbers:")
print(odd_numbers)


Even Numbers:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]
Odd Numbers:
[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]


In [9]:
import numpy as np

# Create two arrays of the same size
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Element-wise addition
result_addition = array1 + array2

# Element-wise subtraction
result_subtraction = array1 - array2

# Element-wise multiplication
result_multiplication = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)

print("Element-wise Addition:", result_addition)
print("Element-wise Subtraction:", result_subtraction)
print("Element-wise Multiplication:", result_multiplication)


Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Element-wise Addition: [ 6  8 10 12]
Element-wise Subtraction: [-4 -4 -4 -4]
Element-wise Multiplication: [ 5 12 21 32]


In [10]:
import numpy as np

# Create the given array
array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

# Sort by rows (ascending order)
sorted_by_row = np.sort(array, axis=1)

# Sort by columns (ascending order)
sorted_by_column = np.sort(array, axis=0)

print("Original Array:")
print(array)

print("Sorted by Row:")
print(sorted_by_row)

print("Sorted by Column:")
print(sorted_by_column)


Original Array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by Row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by Column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [11]:
import numpy as np

# Create the array with NaN values
array = np.array([[4, 2, np.nan, 1],
                  [11, 12, 14, 9],
                  [5, np.nan, 1, np.nan]])

# Find missing data (NaN) and return a Boolean array
missing_data = np.isnan(array)

print("Array with missing data (NaN):")
print(array)

print("Boolean array indicating missing data:")
print(missing_data)


Array with missing data (NaN):
[[ 4.  2. nan  1.]
 [11. 12. 14.  9.]
 [ 5. nan  1. nan]]
Boolean array indicating missing data:
[[False False  True False]
 [False False False False]
 [False  True False  True]]
